name: deploy_develop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      VERSION: latest

    steps:
    # loggear las env
    - name: Log env
      run: echo ${{ env.IMAGE_NAME }}:${{ env.VERSION }}


    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean install --file pom.xml

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

#    - name: Log in to Docker Registry (Private)
#      uses: docker/login-action@v3
#      with:
#        registry: portainer.davidperezmillan.com:5000
#        username: ${{ secrets.REGISTRY_USERNAME }}
#        password: ${{ secrets.REGISTRY_PASSWORD }}
#      continue-on-error: true  # Permite continuar si este paso falla
#
#    - name: Push Docker image to Private Registry
#      run: docker push portainer.davidperezmillan.com:5000/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
#      continue-on-error: true  # Permite continuar si este paso falla

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Tag Docker image for Docker Hub
      run: docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: loggear la WEBHOOKS_STACK
      run: echo ${{ vars.WEBHOOKS_STACK_LATEST }}

    - name: Deploy to Portainer
      run: curl -X POST ${{ vars.WEBHOOKS_STACK_LATEST }}
